---
title: "prep"
output: html_document
date: "`r Sys.Date()`"
---
  
To Do:
* Per-year SSP analysis showing existence and change in SSP over time
* SSP analysis, both pre-latent and contemp, for inflations of interest
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(glue)
library(ggbump)
library(janitor)
library(RColorBrewer)
library(cowplot)

here::i_am("code/analysis.Rmd")
library(here)

proj_root <- here()
```

# Functions

```{r}

calc_inflation_impact <- function(shock_sector_idx, 
                                  shock_pct, 
                                  A,
                                  exogenous_idx,
                                  consump_share_df){
  
  all_idx <- 1:nrow(A)
  X_idx <- sort(unique(c(shock_sector_idx, exogenous_idx)))
  E_idx <- all_idx[!(all_idx %in% X_idx)]
  
  consump_share_X <- 
    consump_share_df %>%
    filter(row_number() %in% X_idx) %>%
    pull(share_personal_consump)
  
  consump_share_E <- 
    consump_share_df %>%
    filter(row_number() %in% E_idx) %>%
    pull(share_personal_consump)
  
  A_EE <- A[E_idx, E_idx]
  A_XE <- A[X_idx, E_idx]
  
  I_mat <- matrix(0, nrow = nrow(A_EE), ncol = ncol(A_EE))
  diag(I_mat) <- 1
  
  dP_X <- matrix(0, nrow = length(X_idx), ncol = 1)
  dP_X_shock_idx <- which(X_idx == shock_sector_idx)
  dP_X[dP_X_shock_idx, 1] <- shock_pct
  
  dP_E <- solve(I_mat - t(A_EE)) %*% t(A_XE) %*% dP_X
  
  impact_df <- 
    tibble(
      impact_dir = as.numeric(consump_share_X %*% dP_X),
      impact_indir = as.numeric(consump_share_E %*% dP_E),
      impact_total = impact_dir + impact_indir
    )
  
  return(impact_df)
}

perform_ssp_analysis <- function(
    analysis_year,
    use_df,
    make_df, 
    import_df,
    industry_codes_df,
    price_index_df,
    total_industry_output_df,
    total_commodity_output_df,
    consumption_df,
    consumption_import_df,
    results_path, 
    exogenous_industry_codes,
    price_vol_range=0, 
    price_change_range=0
    ){
  
    # price_vol_range=0
    # price_change_range=1
  # analysis_year <- 1950
  # input_data_path <- prepared_data_path
  # results_path <- analysis_output_path
  # price_vol_range <- 3
  # 
  dir.create(results_path, recursive = T)

  results_opath <- glue("{results_path}/{analysis_year}_results.csv")
  inflation_impact_plot_path <- glue("{results_path}/{analysis_year}_all_industry_impact.png")

  # EXOGENOUS SECTORS
  sorted_industry_df <-
    industry_codes_df %>%
    arrange(code_name)
  
  always_exogenous_idx <- 
    sorted_industry_df %>%
    mutate(industry_idx = row_number()) %>%
    filter(code %in% exogenous_industry_codes) %>%
    pull(industry_idx)
  
  # CREATE DOMESTIC CONSUMPTION VECTOR
  domestic_consumption_df <- 
    consumption_df %>%
    left_join(
      consumption_import_df,
      by = "commodity"
    ) %>%
    transmute(
      commodity,
      domestic_PCE = F010_Personal_consumption_expenditures - import_PCE
    )
    
  # PULL OUT NEEDED VECTORS
  total_commodity_consumption_vec <-
    domestic_consumption_df %>%
    arrange(commodity) %>%
    pull(domestic_PCE)

  total_commodity_output <- 
    total_commodity_output_df %>%
    arrange(commodity) %>%
    pull(total_output) 
  
  total_industry_output <- 
    total_industry_output_df %>%
    arrange(industry) %>%
    pull(Total_Industry_Output)

  # SORT TABLES
  use_df <- 
    use_df %>%
    arrange(commodity) %>%
    select(sort(colnames(.))) %>%
    select(commodity, everything())

  make_df <- 
    make_df %>%
    arrange(industry) %>%
    select(sort(colnames(.))) %>%
    select(industry, everything())
  
  import_df <- 
    import_df %>%
    arrange(commodity) %>%
    select(sort(colnames(.))) %>%
    select(commodity, everything())    

  # SAFETY CHECK: all columns and rows are aligned
  make_use_commodity_match = !all(colnames(make_df)[2:ncol(make_df)] == use_df$commodity)
  if (make_use_commodity_match){
    stop("make_use_commodity_match")
  }
  
  make_use_industry_match = !all(make_df$industry == colnames(use_df)[2:ncol(use_df)])
  if(make_use_industry_match){
    stop("make_use_industry_match")
  }
  
  import_use_commodity_match = !all(import_df$commodity == use_df$commodity)
  if (import_use_commodity_match){
    stop("import_use_commodity_match")
  }

  import_use_industry_match = !all(colnames(import_df) == colnames(use_df))
  if (import_use_industry_match){
    stop("import_use_industry_match")
  }

  
  # CREATE USE MAT 
  use_mat <- as.matrix(use_df[,2:ncol(use_df)]) 
  import_mat <- as.matrix(import_df[,2:ncol(import_df)]) 

  # DIRECT REQUIREMENT MATRIX
  total_industry_output_imat <- matrix(0, 
                                       nrow = length(total_industry_output),
                                       ncol = length(total_industry_output))
  diag(total_industry_output_imat) <- 1/total_industry_output

  direct_require_mat <- (use_mat - import_mat) %*% total_industry_output_imat
    
  # MARKET SHARE MAT
  total_commodity_output_imat <- matrix(0, 
                                        nrow = length(total_commodity_output),
                                        ncol = length(total_commodity_output))
  diag(total_commodity_output_imat) <- 1/total_commodity_output

  make_mat <-
    make_df %>%
    select(-c(industry)) %>%
    as.matrix()
  
  market_share_mat <- make_mat %*% total_commodity_output_imat
  
  # COEFFICIENT MATRIX AND INVERSE
  iden_mat <- matrix(0, 
                   nrow = nrow(market_share_mat), 
                   ncol = nrow(market_share_mat))
  diag(iden_mat) <- 1

  A <- market_share_mat %*% direct_require_mat
  L <- solve(iden_mat - A)

  # FORWARD LINKAGES
  forward_link_df <- 
    data.frame(
      industry = sorted_industry_df$code_name,
      fl = rowSums(L)
    ) %>%
    arrange(desc(fl)) %>%
    mutate(rank_fl = row_number())
  
  # CONSUMPTION SHARES
  indus_total_consump_vec <- market_share_mat %*% total_commodity_consumption_vec
  indus_share_consump_vec <- indus_total_consump_vec / sum(indus_total_consump_vec)
  indus_share_consump_df <- 
    data.frame(
      industry = sorted_industry_df$code_name,
      share_personal_consump = indus_share_consump_vec
      ) %>%
    mutate(
      share_personal_consump = ifelse(
        share_personal_consump >= 0,
        share_personal_consump, 0),
    )
  
  # CALC SHOCKS
  gross_price_colnames <- colnames(price_index_df)
  time_frame_years <- gross_price_colnames[2:length(gross_price_colnames)] %>% as.numeric()
  
  time_frame_min <- min(time_frame_years)
  time_frame_max <- max(time_frame_years)
    
  # EQUAL ACROSS INDUSTRY
  if (price_vol_range == 0 && price_change_range == 0){
  
    inflation_impact_df <- 
      tibble(
        industry = sorted_industry_df$code_name,
      ) %>%
      mutate(
        industry_idx = row_number(),
        price_shock_pct = 0.01,
        inflation_impact = map2_dfr(
          industry_idx, price_shock_pct, 
          calc_inflation_impact, 
          A, always_exogenous_idx, indus_share_consump_df)
      ) %>%
      unnest(inflation_impact) 
  
  } else if (price_vol_range != 0 && price_change_range == 0) {
    # SHOCKS BASED ON HISTORICAL VOL 
    
    if (analysis_year - price_vol_range < time_frame_min){
      stop()
    }
    
    gross_price_pivot_df <- 
      price_index_df %>%
      pivot_longer(-industry, names_to = "year", values_to = "index") %>%
      mutate(year = as.numeric(year)) %>%
      filter(year <= time_frame_max & year >= time_frame_min)
    
    avg_pct_change_df <- 
      gross_price_pivot_df %>%
      group_by(industry) %>%
      filter(year == analysis_year | year == analysis_year - price_vol_range) %>%
      mutate(
        year_pos = ifelse(year == analysis_year, "end", "start")
      ) %>%
      select(-year) %>%
      pivot_wider(industry, names_from = year_pos, values_from = index) %>%
      mutate(avg_pct_change = (end/start)^(1/(price_vol_range)) - 1)
    
    gross_price_vol_df <- 
      gross_price_pivot_df %>%
      group_by(industry) %>%
      mutate(
        lag1 = lag(index),
        pct_change = (index - lag1)/lag1
        ) %>%
      drop_na() %>%
      left_join(avg_pct_change_df, by = "industry") %>%
      mutate(
        sq_diff_avg_pct_change = (pct_change - avg_pct_change)^2,
      ) %>%
      summarize(
        mean_sq_diff = mean(sq_diff_avg_pct_change),
      ) %>%
      transmute(
        industry,
        price_vol_pct = sqrt(mean_sq_diff)
      )
    
    inflation_impact_df <- 
      tibble(
        industry = sorted_industry_df$code_name,
      ) %>%
      left_join(gross_price_vol_df, by = "industry") %>%
      rename(price_shock_pct = price_vol_pct) %>%
      mutate(
        industry_idx = row_number(),
        inflation_impact = map2_dfr(
          industry_idx, price_shock_pct, 
          calc_inflation_impact, 
          A, always_exogenous_idx, indus_share_consump_df)
      ) %>%
      unnest(inflation_impact) 
    
  } else if (price_vol_range == 0 && price_change_range != 0) {

    if (analysis_year - price_change_range < time_frame_min){
      stop()
    }
    
    gross_price_pivot_df <- 
      price_index_df %>%
      pivot_longer(-industry, names_to = "year", values_to = "index") %>%
      mutate(year = as.numeric(year)) %>%
      filter(year <= time_frame_max & year >= time_frame_min)
    
    avg_pct_change_df <- 
      gross_price_pivot_df %>%
      group_by(industry) %>%
      filter(year == analysis_year | year == analysis_year - price_change_range) %>%
      mutate(
        year_pos = ifelse(year == analysis_year, "end", "start")
      ) %>%
      select(-year) %>%
      pivot_wider(industry, names_from = year_pos, values_from = index) %>%
      transmute(
        industry,
        avg_pct_change = (end/start)^(1/(price_change_range)) - 1
      )
    
    inflation_impact_df <- 
      tibble(
        industry = sorted_industry_df$code_name,
      ) %>%
      left_join(avg_pct_change_df, by = "industry") %>%
      rename(price_shock_pct = avg_pct_change) %>%
      mutate(
        industry_idx = row_number(),
        inflation_impact = map2_dfr(
          industry_idx, price_shock_pct, 
          calc_inflation_impact, 
          A, always_exogenous_idx, indus_share_consump_df)
      ) %>%
      unnest(inflation_impact) 
    
  }
  
  # RESULTS
    
  results_df <- 
    indus_share_consump_df %>%
    left_join(
      forward_link_df,
      by = "industry"
    ) %>%
    left_join(
      inflation_impact_df %>% select(-c(industry_idx)),
      by = "industry"
    ) %>%
    separate(industry, c("industry", "name"), "_", extra = "merge") %>%
    arrange(desc(impact_total)) %>%
    mutate(
      year = analysis_year,
      price_shock_pct = price_shock_pct * 100, 
      share_personal_consump = share_personal_consump *100,
      impact_dir = impact_dir * 100,
      impact_indir = impact_indir * 100,
      impact_total = impact_total * 100,
      impact_rank = row_number()
    ) 

  results_df %>% write_csv(results_opath)
  
  # PLOT
  inflation_impact_plot <- 
      results_df %>%
      filter(!is.na(impact_total)) %>%
      arrange(desc(impact_total)) %>%
      mutate(
        name = str_replace_all(name, "_", " "),
        num = str_pad(row_number(), 2, "left", "0"),
        name = glue("{name} [{num}]")
        ) %>%
      ggplot() + 
      geom_col(aes(x = impact_total, y = fct_reorder(name, impact_total)), 
               color = "darkblue", fill = "darkblue", width = 0.4) + 
      geom_col(aes(x = impact_dir, y = fct_reorder(name, impact_total)), 
               color = "gold", fill = "gold", width = 0.4) +
      ylab("industry") + 
      xlab("inflation impact (%)") + 
      labs(subtitle = glue("Inflation Impact [{analysis_year} IO, price_range: {price_vol_range}, {price_change_range}]")) + 
      theme_light() + 
      theme(axis.text.y = element_text(size = 6))  
      
  ggsave(inflation_impact_plot_path, inflation_impact_plot)
  
  return(list(results_df, inflation_impact_plot))

}

ssp_comparison_wrapper <- 
  function(
    analysis_year, results_path, 
    price_vol_range = 0, price_change_range = 0
  ){
  
  industry_codes_df <- 
    read_csv(glue("{proj_root}/data/prepared/industry_codes_1947.csv"), show_col_types = F)
  price_index_df <- 
    read_csv(glue("{proj_root}/data/prepared/price_index/price_index47.csv"), show_col_types = F)
  exogenous_industry_codes <- c("211", "212", "52", "531", "532RL", "55", "722")
  
  if (analysis_year > 1962){
    
    industry_codes_df <- 
      read_csv(glue("{proj_root}/data/prepared/industry_codes_1963.csv"), show_col_types = F)
    price_index_df <- 
      read_csv(glue("{proj_root}/data/prepared/price_index/price_index63.csv"), show_col_types = F)
    exogenous_industry_codes <- 
      c("211", "212", "521CI", "523", "524", "525", "531", "532RL",
        "55", "621", "622HO", "713", "722")
  }
  
  use_df <- 
    read_csv(glue("{proj_root}/data/prepared/use/{analysis_year}.csv"), show_col_types = F)
  make_df <- 
    read_csv(glue("{proj_root}/data/prepared/make/{analysis_year}.csv"), show_col_types = F)
  import_df <- 
    read_csv(glue("{proj_root}/data/prepared/import/{analysis_year}.csv"), show_col_types = F)
   total_industry_output_df <-
     read_csv(glue("{proj_root}/data/prepared/total_industry_output/{analysis_year}.csv"), show_col_types = F)
  
  total_commodity_output_df <- 
    read_csv(glue("{proj_root}/data/prepared/total_commodity_output/{analysis_year}.csv"), show_col_types = F)
  consumption_df <- 
    read_csv(glue("{proj_root}/data/prepared/commodity_PCE/{analysis_year}.csv"), show_col_types = F)
  consumption_import_df <- 
    read_csv(glue("{proj_root}/data/prepared/commodity_PCE_import/{analysis_year}.csv"), show_col_types = F)
  
  results <- 
    perform_ssp_analysis(
      analysis_year,
      use_df,
      make_df,
      import_df,
      industry_codes_df,
      price_index_df,
      total_industry_output_df,
      total_commodity_output_df,
      consumption_df,
      consumption_import_df,
      results_path, 
      exogenous_industry_codes,
      price_vol_range=price_vol_range, 
      price_change_range=price_change_range
  )

  return(results)
  
}

ssp_comparison <- function(latent_results, inflation_results, 
                           latent_year_str, inflation_year_str,
                           output_path, smaller_title = F){
  
  dir.create(output_path, recursive = T)
  
  results_joint <- 
    left_join(
      latent_results[[1]],
      inflation_results[[1]] %>% select(-name),
      by = "industry",
      suffix = c(".pre", ".inflation")
    ) %>%
    mutate(
      name = str_replace_all(name, "_", " "),
      industry = glue("[{industry}]"),
      code_name = glue("{name} {industry}")
    ) %>%
    filter(!is.na(impact_total.pre)) 
  
  consumption_plot_change <- 
    results_joint %>%
    mutate(      
      code_name = fct_reorder(code_name, impact_total.inflation),
      share_personal_consump.change = share_personal_consump.inflation - share_personal_consump.pre
    ) %>%
    ggplot() + 
    geom_col(aes(x = share_personal_consump.change, y = code_name), fill = "darkgreen") + 
    theme_light() + 
    ylab("sector") +
    xlab("Change in PCE Share") 
  
  fl_plot_change <- 
    results_joint %>%
    mutate(      
      industry = fct_reorder(industry, impact_total.inflation),
      fl.change = fl.inflation - fl.pre
    ) %>%
    ggplot() + 
    geom_col(aes(x = fl.change, y = industry), fill = "purple") + 
    theme_light() + 
    ylab("sector") +
    xlab("Change in Forward Linkages") 
  
  price_shock_change <- 
    results_joint %>%
    mutate(      
      industry = fct_reorder(industry, impact_total.inflation),
       price_shock_pct.change = price_shock_pct.inflation - price_shock_pct.pre
    ) %>%
    ggplot() + 
    geom_col(aes(x = price_shock_pct.change, y = industry), fill = "gray") + 
    theme_light() + 
    ylab("sector") +
    xlab("Change in Price Shock Percent") 

  title <- 
    ggdraw() + 
    draw_label(
      glue("Change in SSP component factors, latent SSP ({latent_year_str}) vs inflationary SSP ({inflation_year_str})"),
    size = 18, x = 0, hjust = -0.25) +
    theme(plot.margin = margin(0, 0, 0, 0))
  
  all_change_plot <- plot_grid(
    consumption_plot_change, fl_plot_change, price_shock_change,
    ncol = 3, rel_widths = c(1.8, 1, 1)
    )
  
  titled_all_change_plot <- plot_grid(
    title, all_change_plot, ncol = 1, rel_heights = c(0.1, 1)
    )
  
  ggsave(
    glue("{output_path}/component_change.png"), 
    titled_all_change_plot, width = 14, bg = "white"
    )
    
  
  dot_compare_plt <- 
    results_joint %>%
    mutate(
      highlight = ifelse(impact_rank.pre <= 10 | impact_rank.inflation <= 10, "T", "F"),
      alpha = ifelse(impact_rank.pre <= 10 | impact_rank.inflation <= 10, 1, 1)
      ) %>%
    pivot_longer(c(impact_rank.pre, impact_rank.inflation), names_to = "period") %>%
    mutate(
      period = str_replace(period, "impact_rank.", ""),
      period = factor(period, levels = c("pre", "inflation"))
      ) %>%
    ggplot() + 
    geom_point(aes(x = period, y = value, color = highlight, fill = highlight)) +
    geom_line(aes(x = period, y = value, group = industry, color = highlight, size = highlight)) + 
    theme_light() + 
    theme(
      legend.position = "none",
      plot.subtitle = element_text(size = 12)
    ) + 
    scale_y_reverse(breaks = scales::pretty_breaks(n = 20), 
                    limits = c(nrow(results_joint), 1),
                    expand = expansion(add = 0.5),
                    ) + 
    scale_size_manual(values = c("T" = 0.9, "F" = 0.5), breaks = c("T", "F")) + 
    scale_color_manual(values = c("T" = "black", "F" = "gray"), breaks = c("T", "F")) + 
    scale_fill_manual(values = c("T" = "black", "F" = "gray"), breaks = c("T", "F")) + 
    scale_x_discrete(expand = c(0.05, 0.05)) + 
    ylab("impact rank") + 
    labs(subtitle = "Comparison of impact ranks") 

  latent_ssp_plot <- 
    latent_results[[2]] + 
    labs(subtitle = glue("Latent SSP {latent_year_str}")) + 
    theme(plot.subtitle = element_text(size = 12))
  
  inflationary_period_ssp_plot <- 
    inflation_results[[2]] + 
    ylab("") + 
    labs(subtitle = glue("Inflationary Period SSP {inflation_year_str}")) + 
    theme(plot.subtitle = element_text(size = 12))
  
  if (smaller_title){
    latent_ssp_plot <- 
      latent_ssp_plot + 
      theme(plot.subtitle = element_text(size = 10))
    
    inflationary_period_ssp_plot <- 
      inflationary_period_ssp_plot + 
      theme(plot.subtitle = element_text(size = 10)) 
    
    dot_compare_plt <- 
      dot_compare_plt + 
      theme(plot.subtitle = element_text(size = 10))
  }
  
  joint_plot <- plot_grid(
    latent_ssp_plot,
    inflationary_period_ssp_plot,
    dot_compare_plt, 
    nrow = 1, rel_widths = c(1, 1, 0.6))
  
  
  ggsave(glue("{output_path}/compare_ssp.png"), joint_plot, width = 14, bg = "white")

}

```

# Long Period Analysis

## Disaggregated

```{r}

results_path <- glue("{proj_root}/results/long_term/all_years")
dir.create(results_path, recursive = T, showWarnings = F)

for (analysis_year in 1948:1996){
  
  print(analysis_year)
  
  use_df <- 
    read_csv(glue("{proj_root}/data/prepared/use/{analysis_year}.csv"), show_col_types = F)
  make_df <- 
    read_csv(glue("{proj_root}/data/prepared/make/{analysis_year}.csv"), show_col_types = F)
  import_df <- 
    read_csv(glue("{proj_root}/data/prepared/import/{analysis_year}.csv"), show_col_types = F)
   total_industry_output_df <-
     read_csv(glue("{proj_root}/data/prepared/total_industry_output/{analysis_year}.csv"), show_col_types = F)
  total_commodity_output_df <- 
    read_csv(glue("{proj_root}/data/prepared/total_commodity_output/{analysis_year}.csv"), show_col_types = F)
  consumption_df <- 
    read_csv(glue("{proj_root}/data/prepared/commodity_PCE/{analysis_year}.csv"), show_col_types = F)
  consumption_import_df <- 
    read_csv(glue("{proj_root}/data/prepared/commodity_PCE_import/{analysis_year}.csv"), show_col_types = F)
  
  industry_codes_df <- 
    read_csv(glue("{proj_root}/data/prepared/industry_codes_1947.csv"), show_col_types = F)
  price_index_df <- 
    read_csv(glue("{proj_root}/data/prepared/price_index/price_index47.csv"), show_col_types = F)
  exogenous_industry_codes <- c("211", "212", "52", "531", "532RL", "55", "722")
  
  if (analysis_year >= 1963){
   
    industry_codes_df <- 
      read_csv(glue("{proj_root}/data/prepared/industry_codes_1963.csv"), show_col_types = F)
    price_index_df <- 
      read_csv(glue("{proj_root}/data/prepared/price_index/price_index63.csv"), show_col_types = F)
    exogenous_industry_codes <- 
       c("211", "212", "521CI", "523", "524", "525", "531", "532RL",
         "55", "621", "622HO", "713", "722")
    
  }
  
  result <- 
    perform_ssp_analysis(
      analysis_year,
      use_df,
      make_df,
      import_df,
      industry_codes_df,
      price_index_df,
      total_industry_output_df,
      total_commodity_output_df,
      consumption_df,
      consumption_import_df,
      results_path, 
      exogenous_industry_codes,
      price_vol_range=0, 
      price_change_range=1
  )

}

```

## Aggregated

```{r}

results_path <- glue("{proj_root}/results/long_term/all_years_agg47")
dir.create(results_path, recursive = T, showWarnings = F)

for (analysis_year in 1948:1996){
  
  print(analysis_year)

  use_df <- 
    read_csv(glue("{proj_root}/data/prepared/use/{analysis_year}.csv"), show_col_types = F)
  make_df <- 
    read_csv(glue("{proj_root}/data/prepared/make/{analysis_year}.csv"), show_col_types = F)
  import_df <- 
    read_csv(glue("{proj_root}/data/prepared/import/{analysis_year}.csv"), show_col_types = F)
   total_industry_output_df <-
     read_csv(glue("{proj_root}/data/prepared/total_industry_output/{analysis_year}.csv"), show_col_types = F)
  
  total_commodity_output_df <- 
    read_csv(glue("{proj_root}/data/prepared/total_commodity_output/{analysis_year}.csv"), show_col_types = F)
  consumption_df <- 
    read_csv(glue("{proj_root}/data/prepared/commodity_PCE/{analysis_year}.csv"), show_col_types = F)
  consumption_import_df <- 
    read_csv(glue("{proj_root}/data/prepared/commodity_PCE_import/{analysis_year}.csv"), show_col_types = F)
  
  industry_codes_df <- 
    read_csv(glue("{proj_root}/data/prepared/industry_codes_1947.csv"), show_col_types = F)
  price_index_df <- 
    read_csv(glue("{proj_root}/data/prepared/price_index/price_index47.csv"), show_col_types = F)
  exogenous_industry_codes <- c("211", "212", "52", "531", "532RL", "55", "722")
  
  if (analysis_year >= 1963){
    
    
  use_df <- 
    read_csv(glue("{proj_root}/data/prepared/agg47_use/{analysis_year}.csv"), show_col_types = F)
  make_df <- 
    read_csv(glue("{proj_root}/data/prepared/agg47_make/{analysis_year}.csv"), show_col_types = F)
  import_df <- 
    read_csv(glue("{proj_root}/data/prepared/agg47_import/{analysis_year}.csv"), show_col_types = F)
   total_industry_output_df <-
     read_csv(glue("{proj_root}/data/prepared/agg47_total_industry_output/{analysis_year}.csv"), show_col_types = F)

  # industry_codes_df <- 
  #     read_csv(glue("{proj_root}/data/prepared/industry_codes_1963_matched.csv"), show_col_types = F) %>%
  #     select(code_name = code_name_match47, code = code_match47, name = name_match47)
   
    # price_index_df <- 
    #   read_csv(glue("{proj_root}/data/prepared/price_index/price_index63.csv"), show_col_types = F)
    # exogenous_industry_codes <- 
    #    c("211", "212", "521CI", "523", "524", "525", "531", "532RL",
    #      "55", "621", "622HO", "713", "722")
    
  }
  
  result <- 
    perform_ssp_analysis(
      analysis_year,
      use_df,
      make_df,
      import_df,
      industry_codes_df,
      price_index_df,
      total_industry_output_df,
      total_commodity_output_df,
      consumption_df,
      consumption_import_df,
      results_path, 
      exogenous_industry_codes,
      price_vol_range=0, 
      price_change_range=1
  )

}


```

## Plotting

```{r}

glob_path <- glue("{proj_root}/results/long_term/all_years_agg47/*.csv")
ssp_csvs <- Sys.glob(glob_path)
ssp_dfs <- lapply(ssp_csvs, read_csv, show_col_types = F)
ssp_df <- bind_rows(ssp_dfs)

ranks_df <- 
  ssp_df %>%
  select(industry, name, impact_rank, year, impact_total) 

```

### Line Plot

```{r}

industry_impact_var_df <- 
  ranks_df %>%
  group_by(industry) %>%
  summarise(impact_var = var(impact_total)) %>%
  arrange(desc(impact_var)) %>%
  mutate(var_rank = row_number())

industry_impact_var_top <- 
  industry_impact_var_df %>%
  arrange(desc(impact_var)) %>%
  slice_head(n = 10) %>%
  pull(industry)

impact_line_plot_df <- 
  ranks_df %>%
  left_join(industry_impact_var_df, by = "industry") %>%
  mutate(
    name = str_replace_all(name, "_", " "),
    code_name = glue("{name} [{industry}]"),
    impact_var_lump = if_else(var_rank < 11, code_name, "Other"), 
    alpha = if_else(var_rank < 11, 1, 0.5),
  ) 

impact_line_plot_cat <- 
  impact_line_plot_df %>%
  filter(impact_var_lump != "Other") %>%
  pull(impact_var_lump) %>% 
  unique() %>%
  sort()

impact_line_plot_cat <- c(impact_line_plot_cat, "Other")

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

industry_palette <- c25[1:(length(impact_line_plot_cat) - 1)]
industry_palette <- c(industry_palette, "black")
names(industry_palette) <- impact_line_plot_cat

impact_line_plot <- 
  impact_line_plot_df %>%
  ggplot() + 
  geom_line(aes(x = year, y = impact_total, group = industry, color = impact_var_lump, alpha = alpha), linewidth = 1) + 
  scale_alpha(guide = 'none') + 
  theme_minimal() +
  theme(
    legend.position="bottom", 
    legend.text=element_text(size=7)
  ) + 
  scale_colour_manual(name = "Industry Sector", values = industry_palette) + 
  xlab("Year") + 
  ylab("Total Inflation Impact") + 
  labs(
    title = "Sector Inflation Impact Varies Over Time",
    subtitle = "Inflation Impact of each Sector Calculated With Yearly Price Change, IO Tables, and Consumption Vector\nSectors with Greatest Impact Variability Are Highlighted"
    )

ggsave(glue("{proj_root}/results/long_term/impact_line_plot.png"), impact_line_plot, width = 10, bg = "white")

```

### Dot Plot

```{r}

impact_dot_df <- 
  ranks_df %>%
  filter(impact_rank <= 10) %>%
  group_by(industry) %>%
  mutate(
    impact_total_fct = case_when(
      impact_total < 0 ~ "< 0%",
      impact_total < 1 ~ "0-1%",
      impact_total < 2 ~ "1-2%",
      impact_total < 3 ~ "2-3%",
      TRUE ~ "> 3%"
    ),
    name = str_replace_all(name, "_", " "),
    industry = glue("[{industry}]"),
    #industry = str_pad(industry, 10),
    code_name = glue("{name}  {industry}"),
    year_diff = year - lag(year) - 1,
    ssp_run = NA
  ) %>%
  arrange(industry, year)

ssp_run_id <- 0
for (i in 1:nrow(impact_dot_df)){
  if (is.na(impact_dot_df$year_diff[i]) || impact_dot_df$year_diff[i] != 0){
    ssp_run_id <- ssp_run_id + 1
    impact_dot_df$ssp_run[i] <- ssp_run_id
  } else {
    impact_dot_df$ssp_run[i] <- ssp_run_id
  }
}

pal <- rev(heat.colors(5))
pal <- brewer.pal(9, "Greys")
#pal <- pal[seq(2, 8, by = 3)]
pal <- pal[c(4, 6, 8)]
#names(pal) <- c("< 0%", "0-1%", "1-2%", "2-3%", "> 3%")
names(pal) <- c("0-1%", "1-2%", "2-3%")

impact_dot_plot <- 
  impact_dot_df %>%
  ggplot() + 
  geom_line(aes(x = year, y = code_name, group = ssp_run)) + 
  geom_point(aes(x = year, y = code_name, size = impact_total_fct, color = impact_total_fct)) + 
  theme_minimal() + 
  scale_size_manual(
    name = "Total Inflation Impact",
    values = c("0-1%"=2, "1-2%"=3, "2-3%"=4),
    breaks = c("0-1%", "1-2%", "2-3%")
  ) + 
  scale_color_manual(
    name = "Total Inflation Impact",
    values = pal,
    breaks = c("0-1%", "1-2%", "2-3%")
  ) + 
  xlab("Year") + 
  ylab("Sector") + 
  labs(
    title = "Several Sectors Remain Top Inflation Impact Sectors Over Decades",
    subtitle = "Top 10 Highest Inflation Impact Sector Selected for Each Year"
    )

ggsave(glue("{proj_root}/results/long_term/impact_dot_plot.png"), impact_dot_plot, bg = "white", width = 12)

```

# Period Analysis 

## analyses 47-62

```{r message=FALSE, warning=FALSE}

analysis_year <- 1950
results_path <- glue("{proj_root}/results/period/SSP-vol")
results50 <- ssp_comparison_wrapper(analysis_year, results_path, price_vol_range=3)

analysis_year <- 1951
results_path <- glue("{proj_root}/results/period/SSP-change")
results51 <- ssp_comparison_wrapper(analysis_year, results_path, price_change_range=1)
 
analysis_year <- 1955
results_path <- glue("{proj_root}/results/period/SSP-vol")
results55 <- ssp_comparison_wrapper(analysis_year, results_path, price_vol_range=8)
  
analysis_year <- 1958
results_path <- glue("{proj_root}/results/period/SSP-change")
results58 <- ssp_comparison_wrapper(analysis_year, results_path, price_change_range=2)

ssp_comparison(results50, results51, "1947-1950", "1950-1951", glue("{proj_root}/results/period/50-51"))

ssp_comparison(results55, results58, "1947-1955", "1956-1958", glue("{proj_root}/results/period/56-58"))

```

## analyses 63-96

```{r message=FALSE, warning=FALSE}

analysis_year <- 1966
results_path <- glue("{proj_root}/results/period/SSP-vol")
results66 <- ssp_comparison_wrapper(analysis_year, results_path, price_vol_range=3)

analysis_year <- 1970
results_path <- glue("{proj_root}/results/period/SSP-change")
results70 <- ssp_comparison_wrapper(analysis_year, results_path, price_change_range=3)

analysis_year <- 1973
results_path <- glue("{proj_root}/results/period/SSP-vol")
results73 <- ssp_comparison_wrapper(analysis_year, results_path, price_vol_range=10)

analysis_year <- 1975
results_path <- glue("{proj_root}/results/period/SSP-change")
results75 <-ssp_comparison_wrapper(analysis_year, results_path, price_change_range = 2)

analysis_year <- 1977
results_path <- glue("{proj_root}/results/period/SSP-vol")
results77 <- ssp_comparison_wrapper(analysis_year, results_path, price_vol_range=14)

analysis_year <- 1980
results_path <- glue("{proj_root}/results/period/SSP-change")
results80 <- ssp_comparison_wrapper(analysis_year, results_path, price_change_range = 2)

ssp_comparison(results66, results70, "1963-1966", "1967-1970", glue("{proj_root}/results/period/67-70"), smaller_title = T)

ssp_comparison(results73, results75, "1963-1973", "1973-1975", glue("{proj_root}/results/period/73-75"), smaller_title = T)

ssp_comparison(results77, results80, "1963-1977", "1978-1980", glue("{proj_root}/results/period/78-80"), smaller_title = T)

```


```{r}

file.copy(
  glue("{proj_root}/results/long_term/impact_line_plot.png"),
  glue("{proj_root}/results/publish/fig01-impact_line_plot.png"),
  overwrite = T
)

file.copy(
  glue("{proj_root}/results/long_term/impact_dot_plot.png"),
  glue("{proj_root}/results/publish/fig02-impact_dot_plot.png"),
  overwrite = T
)

years <- c(
  "50-51", "56-58", "67-70", "73-75", "78-80"
)

i <- 3
for (y in years){
  istr <- str_pad(as.character(i), 2, pad = "0")
  file.copy(
    glue("{proj_root}/results/period/{y}/compare_ssp.png"),
    glue("{proj_root}/results/publish/fig{istr}-{y}-compare_ssp.png"),
    overwrite = T
  )
  i <- i + 1
}

for (y in years){
  istr <- str_pad(as.character(i), 2, pad = "0")
  file.copy(
    glue("{proj_root}/results/period/{y}/component_change.png"),
    glue("{proj_root}/results/publish/fig{istr}-{y}-component_change.png"),
    overwrite = T
  )
  i <- i + 1
}

```


