---
title: "prep"
output: html_document
date: "2023-01-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(glue)
library(janitor)

here::i_am("code/data_prep.Rmd")
library(here)

```

```{r}
proj_root <- here()

downloaded_data_path <- glue("{proj_root}/data/download")
prepared_data_path <- glue("{proj_root}/data/prepared")



make47_xlsx_ipath <- glue("{downloaded_data_path}/IOMake_Before_Redefinitions_1947-1962_Summary.xlsx")
make63_xlsx_ipath <- glue("{downloaded_data_path}/IOMake_Before_Redefinitions_1963-1996_Summary.xlsx")
make97_xlsx_ipath <- glue("{downloaded_data_path}/IOMake_Before_Redefinitions_PRO_1997-2021_Summary.xlsx")

use47_xlsx_ipath <- glue("{downloaded_data_path}/IOUse_Before_Redefinitions_PRO_1947-1962_Summary.xlsx")
use63_xlsx_ipath <- glue("{downloaded_data_path}/IOUse_Before_Redefinitions_PRO_1963-1996_Summary.xlsx")
use97_xlsx_ipath <- glue("{downloaded_data_path}/IOUse_Before_Redefinitions_PRO_1997-2021_Summary.xlsx")

#import97_xlsx_ipath <- glue("{downloaded_data_path}/ImportMatrices_Before_Redefinitions_SUM_1997-2021.xlsx")

gross47_price_xlsx_ipath <- glue("{downloaded_data_path}/GDPbyInd_GO_1947-1997.xlsx")
gross97_price_xlsx_ipath <- glue("{downloaded_data_path}/GrossOutput.xlsx")

gross_price_opath <- glue("{prepared_data_path}/gross_price_index_pct_change.csv")
missing_prices_plot_opath <- glue("{prepared_data_path}/missing_prices_index.png")



price_index_path <- glue("{prepared_data_path}/price_index")

dir.create(price_index_path, recursive = F, showWarnings = F)

prepared_make_data_path <- glue("{prepared_data_path}/make")
dir.create(prepared_make_data_path, recursive = F, showWarnings = F)

prepared_use_data_path <- glue("{prepared_data_path}/use")
dir.create(prepared_use_data_path, recursive = F, showWarnings = F)

prepared_import_data_path <- glue("{prepared_data_path}/import")
dir.create(prepared_import_data_path, recursive = F, showWarnings = F)

total_commodity_output_path <- glue("{prepared_data_path}/total_commodity_output")
consumption_output_path <- glue("{prepared_data_path}/commodity_PCE")
total_industry_output_path <- glue("{prepared_data_path}/total_industry_output")

dir.create(total_commodity_output_path, recursive = F, showWarnings = F)
dir.create(consumption_output_path, recursive = F, showWarnings = F)
dir.create(total_industry_output_path, recursive = F, showWarnings = F)

```


# Prepare downloaded IO data

```{r include=FALSE}

fix_names <- function(df){
  
  # remove rows after addendums
  na_rows <- apply(is.na(df), 1,  all)
  if (any(na_rows)){
    df <- df[-(which(na_rows):nrow(df)), ]
  }
  
  trail_digit_pattern <- regex("_\\d+")
  
  io_code_row_df <- tibble(
    IO_name = pull(df[, 2]), 
    IO_code = if_else(is.na(pull(df[, 1])), "", pull(df[, 1]))
    ) %>%
    slice(-1) %>%
    mutate(
      IO_clean_name = make_clean_names(IO_name, case = "parsed"),
      IO_clean_name = str_replace(IO_clean_name, trail_digit_pattern, ""),
      IO_name_code = if_else(IO_code == "", IO_clean_name, glue("{IO_code}_{IO_clean_name}"))
      )
  
  io_code_col_df <- 
    tibble(
      IO_name = as.character(df[1, ]), 
      IO_code = if_else(
        is.na(colnames(df)) | substr(colnames(df), 1, 3) == "...", "", colnames(df))
      )
  
  if ("Farms" %in% colnames(df)){
      io_code_col_df <-
        tibble(
          IO_code = as.character(df[1, ]), 
          IO_name = if_else(
            is.na(colnames(df)) | substr(colnames(df), 1, 3) == "...", "", colnames(df))
        ) 
  } 

  io_code_col_df <- 
    io_code_col_df %>%
    slice(-c(1, 2)) %>%
    mutate(
      IO_clean_name = make_clean_names(IO_name, case = "parsed"),
      IO_clean_name = str_replace(IO_clean_name, trail_digit_pattern, ""),
      IO_name_code = if_else(IO_code == "", IO_clean_name, glue("{IO_code}_{IO_clean_name}"))
      ) 

  df <- df[-1, -2]
  df[, 1] <- io_code_row_df$IO_name_code
  colnames(df) <- c("sector", io_code_col_df$IO_name_code)
  
  return(df)
  
}

impute_import_domestic_supply <- function(row_trimmed_use_df){
   
   import_pct_df <-
      row_trimmed_use_df %>%
      arrange(commodity) %>%
      mutate(
        positive_imports = F050_Imports_of_goods_and_services > 0,
        # these commodities are not imported and are positive due to port value adjustments
        domestic_supply = Total_Commodity_Output + -1*(F050_Imports_of_goods_and_services) - F040_Exports_of_goods_and_services,
        import_pct_domestic_supply = -1*F050_Imports_of_goods_and_services/domestic_supply,
        import_pct_domestic_supply = if_else(positive_imports, 0, import_pct_domestic_supply)) %>%
      select(c(commodity, import_pct_domestic_supply))
  
}

impute_import_mat <- function(use_df, use_col_trim_end){
  
   trim_use_df <- 
      use_df %>% 
      select(1:use_col_trim_end)
  
   import_pct_df <- 
     impute_import_domestic_supply(use_df)
   
    use_mat <- as.matrix(trim_use_df[,2:use_col_trim_end])
    import_pct_mat <- as.matrix(import_pct_df[, 2])[, rep(1, ncol(use_mat))]
    import_mat <- use_mat * import_pct_mat

    import_df <-
      import_mat %>%
      as_tibble() %>%
      mutate(commodity = trim_use_df$commodity) %>%
      select(commodity, everything()) 
    
    return(import_df)
}

impute_import_PCE <- function(use_df){
  
  import_pct_df <- 
     impute_import_domestic_supply(use_df)
  
  import_PCE_df <- 
    use_df %>%
    arrange(commodity) %>%
    select(commodity, F010_Personal_consumption_expenditures) %>%
    left_join(import_pct_df, by = "commodity") %>%
    transmute(
      commodity,
      import_PCE = import_pct_domestic_supply * F010_Personal_consumption_expenditures
    )
  
  return(import_PCE_df)
  
}

aggregate_IO_table_industries <- function(
    df, 
    industry_code_aggregation_df,
    industries_as_cols = F
  ){
  
  df <- ungroup(df)
  
  if (industries_as_cols){
    
    df <- 
      df %>%
      pivot_longer(-commodity, names_to = "industry", values_to = "value") %>%
      pivot_wider(industry, names_from = "commodity", values_from = "value")
    
  }
  
  agg_df <- 
    left_join(
      df, 
      industry_code_aggregation_df, 
      by = c("industry" = "code_name")
    ) %>%
    mutate(
      code_name_match47 = if_else(
        is.na(code_name_match47), 
        industry, 
        code_name_match47
        )
    ) %>%
    select(-c(industry)) %>%
    pivot_longer(-code_name_match47, names_to = "commodity") %>%
    group_by(commodity, code_name_match47) %>%
    summarise(
      code_name_match47 = unique(code_name_match47), 
      commodity = unique(commodity), 
      value = sum(value),
      .groups = "drop") %>%
    pivot_wider(code_name_match47, names_from = commodity, values_from = value) %>%
    rename(industry = code_name_match47) %>%
    select(industry, everything())
  
  if (industries_as_cols){
    
    agg_df <- 
      agg_df %>%
      pivot_longer(-industry, names_to = "commodity", values_to = "value") %>%
      pivot_wider(commodity, names_from = "industry", values_from = "value")
    
  }

  return(agg_df)

}

prepare_IO <- function(
    prepared_data_path,
    make_file_path,
    use_file_path,
    start_year, 
    end_year,
    make_total_ind_output_colname,
    use_total_commodity_output_colname,
    use_row_trim_start,
    use_col_trim_end,
    make_skip_n = 5,
    use_skip_n = 5,
    import_file_path = NA,
    industry_code_aggregation_df = NA,
    output_prefix = NA
  ){
  
    if (!is.na(industry_code_aggregation_df)){
      
      industry_code_aggregation_df <- ungroup(industry_code_aggregation_df)
      
      colname_match <- 
        colnames(industry_code_aggregation_df) != c("code_name", "code_name_match47")
      
      if (colname_match){
        error("'industry_code_aggregation_df' argument should have colnames (code_name, code_name_match47)")
      }
      
    }
  
    if (is.na(output_prefix)){
      output_prefix <- ""
    }
  
    total_commodity_output_dir <- glue("{prepared_data_path}/total_commodity_output")
    consumption_output_dir <- glue("{prepared_data_path}/commodity_PCE")
    consumption_import_output_dir <- glue("{prepared_data_path}/commodity_PCE_import")

    total_industry_output_dir <-
      glue("{prepared_data_path}/{output_prefix}total_industry_output")
    make_output_dir <- glue("{prepared_data_path}/{output_prefix}make")
    use_output_dir <- glue("{prepared_data_path}/{output_prefix}use")
    import_output_dir <- glue("{prepared_data_path}/{output_prefix}import")
    
    dir.create(total_commodity_output_dir, showWarnings = F)
    dir.create(consumption_output_dir, showWarnings = F)
    dir.create(consumption_import_output_dir, showWarnings = F)
    dir.create(total_industry_output_dir, showWarnings = F)
    dir.create(make_output_dir, showWarnings = F)
    dir.create(use_output_dir, showWarnings = F)
    dir.create(import_output_dir, showWarnings = F)
  
    for (y in seq(start_year, end_year)){
      
      total_commodity_output_path <- glue("{total_commodity_output_dir}/{y}.csv")
      total_industry_output_path <- glue("{total_industry_output_dir}/{y}.csv")
      make_output_path <- glue("{make_output_dir}/{y}.csv")
      consumption_output_path <- glue("{consumption_output_dir}/{y}.csv")
      consumption_import_output_path <- glue("{consumption_import_output_dir}/{y}.csv")
      use_output_path <- glue("{use_output_dir}/{y}.csv")
      import_output_path <- glue("{import_output_dir}/{y}.csv")
      industry_codes_output_path <- glue("{prepared_data_path}/industry_codes_{start_year}.csv")
      
      print(y)
      
      # MAKE
      make_df <- 
        read_xlsx(make_file_path, sheet = as.character(y), skip = make_skip_n) %>%
        fix_names() %>%
        pivot_longer(-sector) %>%
        mutate(
          value = if_else(value == "...", "0", value),
          value = as.numeric(value)) %>%
        pivot_wider(sector) %>%
        rename("Total_Industry_Output" = !!make_total_ind_output_colname)
      colnames(make_df)[1] <- "industry"
      
      # store industry codes, always unaggregated
      make_df %>%
        select(industry) %>%
        separate(industry, c("code", "name"), 
                 sep = "_", extra = "merge", remove = F) %>%
        rename(code_name = industry) %>%
        slice(-nrow(.)) %>%
        write_csv(industry_codes_output_path)
      
      # aggregate industry if needed
      if (
        is_tibble(industry_code_aggregation_df) & 
        !is_empty(industry_code_aggregation_df)){
        make_df <- 
          aggregate_IO_table_industries(
            make_df, industry_code_aggregation_df)
      }
      
      # store totals
      make_df %>%
        slice(nrow(.)) %>%
        select(-c(industry, Total_Industry_Output)) %>%
        select(all_of(sort(colnames(.)))) %>% 
        pivot_longer(everything(), names_to = "commodity", values_to = "total_output") %>%
        write_csv(total_commodity_output_path)
      
      make_df %>%
        arrange(industry) %>%
        slice(-nrow(.)) %>%
        select(c(industry, Total_Industry_Output)) %>%
        write_csv(total_industry_output_path)
      
      # store matrix
      make_df %>%
        slice(-nrow(.)) %>%
        select(-Total_Industry_Output) %>%
        write_csv(make_output_path)
      
      # USE
      use_df <- 
        read_xlsx(use_file_path, sheet = as.character(y), skip = use_skip_n) %>%
        fix_names() %>%
        pivot_longer(-sector) %>%
        mutate(
          value = if_else(value == "...", "0", value),
          value = as.numeric(value)) %>%
        pivot_wider(sector) %>%
        rename("Total_Commodity_Output" = !!use_total_commodity_output_colname) %>%
        slice(-(use_row_trim_start:nrow(.)))
      colnames(use_df)[1] <- "commodity"
      
      trim_use_df <- 
        use_df %>% 
        select(1:use_col_trim_end)
      
      #IMPORT - put here to use non-aggregated use if imputing
      if (!is.na(import_file_path)){
        
        import_df <- 
          read_xlsx(import_file_path, sheet = as.character(y), skip = 5) %>%
          fix_names() %>%
          pivot_longer(-sector) %>%
          mutate(
            value = if_else(value == "...", "0", value),
            value = as.numeric(value)) %>%
          pivot_wider(sector) 
        colnames(import_df)[1] <- "commodity"
  
      } else {
        import_df <- 
          impute_import_mat(use_df, use_col_trim_end)
      }
      
      # aggregate industry if needed
      if (
        is_tibble(industry_code_aggregation_df) & 
        !is_empty(industry_code_aggregation_df)){
        use_df <- 
          aggregate_IO_table_industries(
            use_df, industry_code_aggregation_df, industries_as_cols = T)
        
        trim_use_df <- 
          aggregate_IO_table_industries(
            trim_use_df, industry_code_aggregation_df, industries_as_cols = T)
        
        import_df <- 
          aggregate_IO_table_industries(
            import_df, industry_code_aggregation_df, industries_as_cols = T)
      }
      
      import_df %>% write_csv(import_output_path)
      trim_use_df %>% write_csv(use_output_path)

      # continue with use df
      use_df %>%
        arrange(commodity) %>%
        select(c(commodity, F010_Personal_consumption_expenditures)) %>%
        write_csv(consumption_output_path)
      
      impute_import_PCE(use_df) %>%
        write_csv(consumption_import_output_path)
      
    }

}

```

```{r echo=TRUE}

prepare_IO(
    prepared_data_path,
    make47_xlsx_ipath,
    use47_xlsx_ipath,
    1947, 
    1962,
    make_total_ind_output_colname = "T008_Total_Industry_Output",
    use_total_commodity_output_colname = "T007_Total_Commodity_Output",
    use_row_trim_start = 50,
    use_col_trim_end = 48
    )

prepare_IO(
    prepared_data_path,
    make63_xlsx_ipath,
    use63_xlsx_ipath,
    1963, 
    1996,
    make_total_ind_output_colname = "T008_Total_Industry_Output",
    use_total_commodity_output_colname = "T007_Total_Commodity_Output",
    use_row_trim_start = 68,
    use_col_trim_end = 66
    )

prepare_IO(
    prepared_data_path,
    make97_xlsx_ipath,
    use97_xlsx_ipath,
    1997, 
    2021,
    make_total_ind_output_colname = "Total_Industry_Output",
    use_total_commodity_output_colname = "Total_Commodity_Output",
    use_row_trim_start = 68,
    use_col_trim_end = 66
    )



```


## Standardize industry aggregation across time periods

```{r}

match_codes_prev_period <- function(period_47_df, period_other_df, force_match_df = tibble()){
  
  period_other_df <- 
    period_other_df %>%
    mutate(
      code_match47 = if_else(code %in% period_47_df$code, code, NA),
      code_short = code
    )
  
  if (!is_empty(force_match_df)){
    period_other_df <- 
      period_other_df %>%
      left_join(force_match_df, by = "code") %>%
      mutate(code_match47 = if_else(!is.na(force_match_code), force_match_code, code_match47)) %>%
      select(-c(force_match_code))
  }
  
  while(
    any(is.na(period_other_df$code_match47)) &&
    !any(period_other_df$code_short == "", na.rm = T) # means no match possible for at least 1
    ){
    
    print(sum(is.na(period_other_df$code_match47)))
    
    period_other_df <- 
      period_other_df %>%
      mutate(
        code_short = if_else(is.na(code_match47), str_sub(code_short, end = -2), NA),
        code_short_match = code_short %in% period_47_df$code,
        code_match47 = if_else(is.na(code_match47) & code_short_match, code_short, code_match47)
      )
  }
  
  if (any(is.na(period_other_df$code_match47))){
    print("failed to match at least one industry")
  } else{
    period_other_df <- 
      period_other_df %>% 
      select(-c(code_short, code_short_match)) %>%
      left_join(
        period_47_df %>% rename(name_match47 = name, code_name_match47 = code_name),
        by = c("code_match47" = "code")
        )
  }
  
  return(period_other_df)
  
}

```


```{r}

industry_codes47_df <- read_csv(glue("{prepared_data_path}/industry_codes_1947.csv"))
industry_codes63_df <- read_csv(glue("{prepared_data_path}/industry_codes_1963.csv"))
industry_codes97_df <- read_csv(glue("{prepared_data_path}/industry_codes_1997.csv"))

force_match97_df <- tibble(
  code = c("HS", "ORE", "441", "445", "452", "4A0"), 
  force_match_code = c("531", "531", "44RT", "44RT", "44RT", "44RT")
  )
force_match97_df %>% write_csv(glue("{prepared_data_path}/force_match_industry_codes_1997to47.csv"))

mod_industry_codes63_df <-
  match_codes_prev_period(industry_codes47_df, industry_codes63_df)
mod_industry_codes97_df <- 
  match_codes_prev_period(industry_codes47_df, industry_codes97_df, force_match97_df)

mod_industry_codes63_df %>% write_csv(glue("{prepared_data_path}/industry_codes_1963_matched.csv"))
mod_industry_codes97_df %>% write_csv(glue("{prepared_data_path}/industry_codes_1997_matched.csv"))

```


## Combine IO tables to 1947 levels for long term analysis

```{r}

prepare_IO(
    prepared_data_path,
    make63_xlsx_ipath,
    use63_xlsx_ipath,
    1963, 
    1996,
    make_total_ind_output_colname = "T008_Total_Industry_Output",
    use_total_commodity_output_colname = "T007_Total_Commodity_Output",
    use_row_trim_start = 68,
    use_col_trim_end = 66,
    industry_code_aggregation_df = 
      mod_industry_codes63_df %>% select(c(code_name, code_name_match47)),
    output_prefix = "agg47_"
    )

prepare_IO(
    prepared_data_path,
    make97_xlsx_ipath,
    use97_xlsx_ipath,
    1997, 
    2021,
    make_total_ind_output_colname = "Total_Industry_Output",
    use_total_commodity_output_colname = "Total_Commodity_Output",
    use_row_trim_start = 68,
    use_col_trim_end = 66,
    industry_code_aggregation_df = 
      mod_industry_codes97_df %>% select(c(code_name, code_name_match47)),
    output_prefix = "agg47_"
    )


```


## Price Index 

```{r}

subset_price_index_df <- function(price_df, industry_codes_df, post1997 = F, edit_transporation = F){
  
  # remove "All industries" and "private industries" row 
  price_df <- slice(price_df, -c(1, 2))
  
  # find and remove footnotes
  footnotes_idx <- which("Addenda:" == price_df[,2])
  price_df <- price_df[-c(footnotes_idx: nrow(price_df)), ]
  
  # remove line column
  if (post1997){
    price_df <- price_df[, -c(1, 3)]
  } else{
    price_df <- price_df[, -1]
  }
  
  # rename column to industry
  colnames(price_df)[1] <- "industry"
  
  # clean industry names
  price_df$industry <- make_clean_names(price_df$industry, case = "parsed")
    
  # hard code some name changes
  price_df <- 
    price_df %>%
    mutate(industry = case_when(
      industry == "National_defense" ~ "Federal_general_government_defense",
      industry == "Nondefense" ~ "Federal_general_government_nondefense",
      industry == "Government_enterprises" ~ "Federal_government_enterprises",
      industry == "General_government_2" ~ "State_and_local_general_government",
      industry == "Government_enterprises_2" ~ "State_and_local_government_enterprises",
      industry == "General_government" ~ "Federal_general_government",
      (industry == "Transportation_and_warehousing") & edit_transporation ~ "Transportation",
      TRUE ~ industry
    ))

  # find matching codes
  industry_codes_df <- 
    industry_codes_df %>%
    mutate(price_match_name = NA, price_match_idx = NA)
    
  for (i in 1:nrow(price_df)){
    
    price_industry <- price_df$industry[i]
    
    if (price_industry %in% industry_codes_df$name){
      
      match_idx <- which(price_industry == industry_codes_df$name)
      
      industry_codes_df[match_idx, "price_match_idx"] <-
        ifelse(is.na(industry_codes_df[match_idx, "price_match_idx"]), 
               i, 
               paste("*", industry_codes_df[match_idx, "price_match_idx"], i))
      
      industry_codes_df[match_idx, "price_match_name"] <-
        ifelse(is.na(industry_codes_df[match_idx, "price_match_name"]), 
               industry_codes_df$name[match_idx], 
               paste("*", industry_codes_df[match_idx, "price_match_name"], i))
    }
  }
  
  # swap names in price_df 
  join_price_df <- left_join(
    price_df, industry_codes_df, by = c("industry" = "name"), keep = T) %>%
    drop_na() %>%
    mutate(industry = code_name) %>%
    select(-all_of(colnames(industry_codes_df))) %>%
    mutate(across(everything(), .fns = ~ replace(.x, which(.x == "..."), NA)))
  
  return(join_price_df)
  
}

plot_missing_prices <- function(df, output_path){
   
  # make image of missing prices
  industries_with_missing <-
    df %>%
    mutate(industry = factor(industry, levels = industry)) %>%
    pivot_longer(-industry, names_to = "year", values_to = "price_index") %>%
    group_by(industry) %>%
    summarise(any_na = any(is.na(price_index))) %>%
    filter(any_na)

  n_industries_with_missing <- nrow(industries_with_missing)
  
  missing_prices_heatmap <-  
    df %>%
    mutate(industry = factor(industry, levels = industry)) %>%
    pivot_longer(-industry, names_to = "year", values_to = "price_index") %>%
    ggplot() + 
    geom_tile(aes(x = year, y = industry, fill = is.na(price_index)), color = "black") + 
    theme(
      axis.text.y = element_text(size = 6),
      axis.text.x = element_text(angle = 45, hjust = 1)
    ) +
    labs(subtitle = glue("industries with some some missing prices = {n_industries_with_missing}")) 
  
  ggsave(output_path, missing_prices_heatmap, width = 15)
  
}

```


```{r}

price47_df <- read_xlsx(gross47_price_xlsx_ipath, sheet = "ChainPriceIndexes", skip = 5)
price97_df <- read_xlsx(gross97_price_xlsx_ipath, sheet = "TGO104-A", skip = 7) 

industry_codes47_df <- read_csv(glue("{prepared_data_path}/industry_codes_1947.csv"))
industry_codes63_df <- read_csv(glue("{prepared_data_path}/industry_codes_1963.csv"))
industry_codes97_df <- read_csv(glue("{prepared_data_path}/industry_codes_1997.csv"))

mod_price47_df <- 
  subset_price_index_df(price47_df, industry_codes47_df, edit_transporation = T) %>%
  select(-`1997`)

mod_price63_df <- 
  subset_price_index_df(price47_df, industry_codes63_df, edit_transporation = T) %>% 
  select(-`1997`)

mod_price97_df <- 
  subset_price_index_df(price97_df, industry_codes97_df, post1997 = T)

mod_price97_match47_df <- 
  subset_price_index_df(price97_df, industry_codes47_df, post1997 = T, edit_transporation = T)

mod_price47_df %>% write_csv(glue("{price_index_path}/price_index47.csv"))
mod_price63_df %>% write_csv(glue("{price_index_path}/price_index63.csv"))
mod_price97_df %>% write_csv(glue("{price_index_path}/price_index97.csv"))
mod_price97_match47_df %>% write_csv(glue("{price_index_path}/price_index97_match47.csv"))

plot_missing_prices(mod_price47_df, glue("{price_index_path}/price_index47_missing.png"))
plot_missing_prices(mod_price63_df, glue("{price_index_path}/price_index63_missing.png"))
plot_missing_prices(mod_price97_df, glue("{price_index_path}/price_index97_missing.png"))
plot_missing_prices(mod_price97_match47_df, glue("{price_index_path}/price_index97_match47_missing.png"))

```

